<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!-- 基础配置 -->
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>disable</Nullable>
		<ApplicationIcon>icon.ico</ApplicationIcon>
		<AssemblyTitle>EVE BOX</AssemblyTitle>
		<AssemblyName>EVE BOX</AssemblyName>
		<RootNamespace>EVEBox</RootNamespace>

		<!-- 发布配置：生成单个文件 -->
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<PublishReadyToRun>true</PublishReadyToRun>
		<PublishTrimmed>false</PublishTrimmed>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

		<!-- 排除测试目录，避免被主项目编译 -->
		<DefaultItemExcludes>$(DefaultItemExcludes);tests\**</DefaultItemExcludes>
	</PropertyGroup>
</Project>